baseurl = "http://keyboardjunk.com"
languageCode = "en"
title = "Keyboard Junk"
copyright = ""
paginate = 3

googleAnalytics = "Yout Google Analytics ID"

theme = "minimage"

[params]
  description = "snacksthecat on Deskthority and Reddit"
  author = "snacksthecat"
  logo = '/image/logo.png'

[[menu.global]]
    name = "Development"
    url = "/categories/Development/"

[[menu.footer]]
    name = "About"
    url = "/page/about/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
