baseurl = "https://keyboardjunk.com"
languageCode = "en-us"
title = "Keyboard Junk"
theme = "minimage"

copyright = ""
googleAnalytics = ""

disqusShortname = ""
paginate = 5

canonifyurls = true

[params]
  description = "snacksthecat on Deskthority and Reddit"
  cover = "images/cover.jpg"
  author = ""
  authorlocation = ""
  authorwebsite = ""
  bio= ""
  logo = "images/logo.png"
  googleAnalyticsUserID = ""
  RSSLink = ""
  githubName = ""
  twitterName = ""
  hideHUGOSupport = false
  [params.social]
    twitter = ""

[[menu.global]]
    name = "Blog"
    url = "/"

[[menu.global]]
    name = "About"
    url = "/about/"