baseurl = "/"
languageCode = "en-us"
title = "Casper Theme"
theme = "minimage"

copyright = ""
googleAnalytics = ""

disqusShortname = ""
paginate = 5

canonifyurls = true

[params]
  description = "snacksthecat on Deskthority and Reddit"
  cover = "images/cover.jpg"
  author = ""
  authorlocation = ""
  authorwebsite = ""
  bio= ""
  logo = "images/logo.png"
  googleAnalyticsUserID = ""
  RSSLink = ""
  githubName = ""
  twitterName = ""
  hideHUGOSupport = false
  [params.social]
    twitter = ""
